import 'dart:convert';

import 'package:flutter/foundation.dart';

import '../demo_backend.dart';
import '../demo_world.dart';

/// Who is signed in, the one organization and the Boardhop project.
void registerCoreFixtures(DemoBackend b, {Uint8List? projectPicture}) {
  final me = DemoWorld.me;

  b.get(
    r'app\.vssps\.visualstudio\.com/_apis/profile/profiles/me',
    (_) => {
      'id': me.id,
      'displayName': me.name,
      'emailAddress': me.email,
      'publicAlias': me.id,
    },
  );

  b.get(
    r'app\.vssps\.visualstudio\.com/_apis/accounts',
    (_) => [
      {
        'accountId': DemoWorld.orgId,
        'accountName': DemoWorld.org,
        'accountUri': 'https://vssps.dev.azure.com/${DemoWorld.org}/',
        'properties': {
          'Microsoft.VisualStudio.Services.Account.TenantId': {
            '\$type': 'System.String',
            '\$value': DemoWorld.tenantId,
          },
        },
      },
    ],
  );

  final project = {
    'id': DemoWorld.projectId,
    'name': DemoWorld.project,
    'description': DemoWorld.projectDescription,
    'url': '${DemoWorld.baseUrl}/_apis/projects/${DemoWorld.projectId}',
    'state': 'wellFormed',
    'revision': 412,
    'visibility': 'private',
    'lastUpdateTime': DemoWorld.iso(DemoWorld.hoursAgo(3)),
    'defaultTeam': {
      'id': DemoWorld.teamId,
      'name': DemoWorld.team,
      'url':
          '${DemoWorld.baseUrl}/_apis/projects/${DemoWorld.projectId}/teams/${DemoWorld.teamId}',
    },
  };

  b.get('dev\\.azure\\.com/${DemoWorld.org}/_apis/projects', (_) => [project]);
  b.get(
    'dev\\.azure\\.com/${DemoWorld.org}/_apis/projects/(${DemoWorld.projectId}|${DemoWorld.project})',
    (_) => project,
  );
  b.get(
    'vssps\\.dev\\.azure\\.com/${DemoWorld.org}/_apis/graph/descriptors/${DemoWorld.teamId}',
    (_) => {'value': DemoWorld.teamDescriptor},
  );

  // The project's picture is its default team's: the Boardhop icon.
  final picture = projectPicture == null ? null : base64Encode(projectPicture);
  b.get(
    'vssps\\.dev\\.azure\\.com/${DemoWorld.org}/_apis/graph/[Ss]ubjects/${DemoWorld.teamDescriptor}/avatars',
    (_) => picture == null
        ? const DemoResponse(404)
        : {'isAutoGenerated': false, 'size': 'large', 'value': picture},
  );

  // No photos: the app draws initials, as Azure DevOps does for people who
  // never uploaded one.
  b.get(
    'vssps\\.dev\\.azure\\.com/${DemoWorld.org}/_apis/graph/[Ss]ubjects/[^/]+/avatars',
    (_) => const DemoResponse(404),
  );
}
